name: todomaui-dev

services:
  postgres-dev:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ToDoMauiDev
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5444:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql
 
volumes:
  dev_db_data:
